const { Client } = require('pg');
require('dotenv').config();

const client = new Client({
  user: process.env.DB_USER,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port: process.env.DB_PORT,
});

async function run() {
  await client.connect();
  console.log("Connected to database. Generating over 10,000 records...");

  // 1. Insert 2,000 Customers
  console.log("Inserting 2,000 customers...");
  for (let i = 1; i <= 2000; i++) {
    await client.query(`
      INSERT INTO customers (first_name, last_name, email) 
      VALUES ('Customer_First_${i}', 'Customer_Last_${i}', 'user_${i}@example.com')
      ON CONFLICT (email) DO NOTHING;
    `);
  }

  // 2. Insert 1,000 Products (Using JSONB attributes field)
  console.log("Inserting 1,000 products...");
  for (let i = 1; i <= 1000; i++) {
    const jsonAttributes = {
      color: i % 2 === 0 ? 'Red' : 'Blue',
      weight_g: 100 + i,
      category: i % 3 === 0 ? 'Electronics' : 'Apparel'
    };
    
    await client.query(`
      INSERT INTO products (sku, name, price, stock_quantity, attributes) 
      VALUES ('SKU-PROD-${i}', 'Product Item ${i}', ${(15 + i * 0.25).toFixed(2)}, 5000, $1)
      ON CONFLICT (sku) DO NOTHING;
    `, [JSON.stringify(jsonAttributes)]);
  }

  // 3. Insert 3,000 Orders with 3 items each (Total = 9,000 Order Items)
  console.log("Generating orders and items (this may take a few seconds)...");
  
  // Fetch real IDs generated by the database
  const customerRows = await client.query('SELECT customer_id FROM customers LIMIT 200');
  const productRows = await client.query('SELECT product_id, price FROM products LIMIT 200');

  for (let i = 1; i <= 3000; i++) {
    // Pick a random customer
    const randomCustomer = customerRows.rows[Math.floor(Math.random() * customerRows.rows.length)].customer_id;
    
    // Create the order parent record
    const orderResult = await client.query(`
      INSERT INTO orders (customer_id, status) VALUES ($1, 'Completed') RETURNING order_id;
    `, [randomCustomer]);
    const orderId = orderResult.rows[0].order_id;

    // Insert 3 separate items per order to securely push us way past the 10,000 threshold
    for (let j = 0; j < 3; j++) {
      const randomProduct = productRows.rows[Math.floor(Math.random() * productRows.rows.length)];
      
      await client.query(`
        INSERT INTO order_items (order_id, product_id, quantity, unit_price) 
        VALUES ($1, $2, $3, $4);
      `, [orderId, randomProduct.product_id, Math.floor(Math.random() * 3) + 1, randomProduct.price]);
    }
  }

  // Verification counts
  const totalCustomers = await client.query('SELECT COUNT(*) FROM customers');
  const totalProducts = await client.query('SELECT COUNT(*) FROM products');
  const totalOrderItems = await client.query('SELECT COUNT(*) FROM order_items');
  
  console.log("\n--- DATA POPULATION REPORT ---");
  console.log(`Customers created: ${totalCustomers.rows[0].count}`);
  console.log(`Products created: ${totalProducts.rows[0].count}`);
  console.log(`Order Items created: ${totalOrderItems.rows[0].count}`);
  console.log("Success! Total volume exceeds 12,000 records.");

  await client.end();
}

run().catch(console.error);